[project]
name = "my_kaggle_util"
version = "0.1"
readme = 'README.md'
requires-python = '>=3.9'
license = {file = 'LICENSE'}
authors = [{name = 'Kazuki Negita', email = 'welshonionman@gmail.com'}]
dependencies = [
    'kaggle',
]